services:

  selenium-hub:
    image: selenium/hub:4.20.0
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.20.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub

  firefox:
    image: selenium/node-firefox:4.20.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub

  tests:
    build: .
    depends_on:
      - chrome
      - firefox
    environment:
      - GRID_URL=http://selenium-hub:4444/wd/hub
      - BROWSER=chrome
